### ISSUE TITLE
update readme file 

### ISSUE THREAD

**Issue by PavvanPradeep** [PavvanPradeep/hacktoberfest#1]
add more stuff to readme file

**Comment by vedamruta** [comment]
Please assign me to this issue. I would like to update the README file of your repo in order to create awareness about Opensource and Hacktoberfest. :)

**Comment by PavvanPradeep** [comment]
@vedamruta im sorry but this repo was for testing something i will be deleting it soon

**Comment by vedamruta** [comment]
Oh no problem :)
